# Пушка Shank: PA dmg 125, RoF 0.9, range 100, vel 150.

id   = "shank_cannon"
base = "/tools/base_weapon.toml"
name = "Пушка Шэнка"

range             = 6.7
damage            = 125.0
fire_interval     = 1.111
projectile_speed  = 10.0
spread_degrees    = 2.5
projectile_radius = 0.09
projectile_color  = [1.0, 0.5, 0.35]
