# Орудие турели: PA dmg 60, RoF 2, range 100, vel 500.

id   = "turret_gun"
base = "/tools/base_weapon.toml"
name = "Орудие турели"

range             = 6.7
damage            = 65.0
fire_interval     = 0.35
projectile_speed  = 33.3
spread_degrees    = 2.0
projectile_radius = 0.07
projectile_color  = [0.64, 0.8, 1]
